// import type { Metadata } from "next";
// import { Poppins, Quicksand } from "next/font/google";
// import "./globals.css";
// import Layout from "@/components/Layout";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "600"],
//   variable: "--font-poppins",
// });

// const quicksand = Quicksand({
//   subsets: ["latin"],
//   weight: ["600", "700"],
//   variable: "--font-quicksand",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//          className={`${poppins.variable} ${quicksand.variable} antialiased`}
//       >
//         <Layout>{children}</Layout>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; 
import "./globals.css";
import Layout from "@/components/Layout";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "800"], 
  variable: "--font-inter",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Pantea Ghaffari | Next.js Developer Portfolio", 
  description: "A high-performance portfolio showcasing Next.js and React expertise.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`${inter.variable} ${robotoMono.variable} font-sans antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}